{
 "title": "Prometheus Internal Stats",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "query_result(prometheus_tsdb_blocks_loaded)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "query_result(up{job=~\"$job\"})"
    }
   },
   {
    "name": "interval",
    "query": "5m, 10m, 30m, 1h, 3h, 6h, 12h, 1d, 2d, 7d, 30d, 90d, 180d"
   }
  ]
 },
 "panels": [
  { "title": "at a glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job=\"prometheus\"}[$interval]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "description": "Prometheus Memory Usage in relation to total memory available",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(process_resident_memory_bytes{job=\"prometheus\"} * 100) / scalar(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Resident Memory",
   "type": "stat",
   "description": "Resident set memory size is number of memory pages the process has in real memory, with pagesize. This results in the amount of memory that belongs specifically to that process in bytes. This excludes swapped out memory pages.",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"prometheus\"}"
    }
   ]
  },
  {
   "title": "Uptime [$interval]",
   "type": "stat",
   "description": "Percentage of uptime during the most recent $interval period.  Change the period with the 'interval' dropdown above.",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{instance=~\"$instance\",job=~\"$job\"}[$interval]) * 100)"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "stat",
   "description": "Total number of time series in prometheus",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Local Storage ",
   "type": "stat",
   "description": "The number of bytes that are currently used for local storage by all blocks.",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_storage_blocks_bytes"
    }
   ]
  },
  {
   "title": "Samples Ingested /s",
   "type": "stat",
   "description": "Samples Ingested per second through scraping activity",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total[$interval])"
    }
   ]
  },
  {
   "title": "Head Block Retention",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_max_time - prometheus_tsdb_head_min_time"
    }
   ]
  },
  {
   "title": "Memory Chunks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Samples Per Chunk",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_compaction_chunk_samples_sum[6h])/rate(prometheus_tsdb_compaction_chunk_samples_count[6h])",
     "legendFormat": "series"
    }
   ]
  },
  {
   "title": "Head Chunk Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(prometheus_tsdb_head_chunks * (prometheus_tsdb_compaction_chunk_samples_sum / prometheus_tsdb_compaction_chunk_samples_count) * 1.5)"
    }
   ]
  },
  {
   "title": "quick numbers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missed Iterations [$interval]",
     "type": "stat",
     "description": "The total number of rule group evaluations missed due to slow rule group evaluation.",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_rule_group_iterations_missed_total{job=~\"$job\",instance=~\"$instance\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Skipped Iterations [$interval]",
     "type": "stat",
     "description": "The total number of rule group evaluations skipped due to throttled metric storage.",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_evaluator_iterations_skipped_total{job=~\"$job\",instance=~\"$instance\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Tardy Scrapes [$interval]",
     "type": "stat",
     "description": "Total number of scrapes that hit the sample limit and were rejected.",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\",instance=~\"$instance\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Reload Failures [$interval]",
     "type": "stat",
     "description": "Number of times the database failed to reload block data from disk.",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_tsdb_reloads_failures_total{job=~\"$job\",instance=~\"$instance\"}[$interval]))"
      }
     ]
    },
    {
     "title": "Skipped Scrapes [$interval]",
     "type": "stat",
     "description": "Sum of all skipped scrapes",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_bounds_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_order_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) "
      }
     ]
    }
   ]
  },
  {
   "title": "resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "irate(process_cpu_seconds_total{job=\"prometheus\",instance=\"$instance\"}[$interval])",
       "legendFormat": "Irate"
      },
      {
       "expr": "rate(process_cpu_seconds_total{job=\"prometheus\",instance=\"$instance\"}[$interval])",
       "legendFormat": "5m rate"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"prometheus\",instance=\"$instance\"}",
       "legendFormat": "RSS"
      },
      {
       "expr": "prometheus_local_storage_target_heap_size_bytes{job=\"prometheus\",instance=\"$instance\"}",
       "legendFormat": "Target heap size"
      },
      {
       "expr": "go_memstats_next_gc_bytes{job=\"prometheus\",instance=\"$instance\"}",
       "legendFormat": "Next GC"
      },
      {
       "expr": "go_memstats_alloc_bytes{job=\"prometheus\",instance=\"$instance\"}",
       "legendFormat": "Allocated"
      }
     ]
    }
   ]
  },
  {
   "title": "durations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rule Group Evaluation Quantiles",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "prometheus_rule_group_duration_seconds{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Last Rule Group Evaluation Duration",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "prometheus_rule_group_last_duration_seconds{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "{{ rule_group }}"
      }
     ]
    },
    {
     "title": "Rule Evaluation Quantiles",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "prometheus_rule_evaluation_duration_seconds{quantile=\"0.5\", job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "P50"
      },
      {
       "expr": "prometheus_rule_evaluation_duration_seconds{quantile=\"0.9\", job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "P90"
      },
      {
       "expr": "prometheus_rule_evaluation_duration_seconds{quantile=\"0.99\", job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "Rule Group Iterations Missed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Changes per second" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_rule_group_iterations_missed_total{job=\"$job\", instance=\"$instance\"}[$interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Rule Evaluation Failures",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "Changes Per Second" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_rule_evaluation_failures_total{job=\"$job\", instance=\"$instance\"}[$interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "HTTP Request Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 37 },
     "yaxes": [
      { "format": "s", "label": "Microseconds" }
     ],
     "targets": [
      {
       "expr": "sum by (handler) (rate(prometheus_http_request_duration_seconds_count{job=\"$job\", instance=\"$instance\"}[$interval])) ",
       "legendFormat": "{{handler}}"
      }
     ]
    },
    {
     "title": "HTTP Request Duration Quantiles",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 37 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum(rate(prometheus_http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$interval])) by (le))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(rate(prometheus_http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$interval])) by (le))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(prometheus_http_request_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[$interval])) by (le))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "Prometheus Engine Query Duration Seconds",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_engine_query_duration_seconds_sum{job=~\"$job\",instance=~\"$instance\"}) by (slice)",
       "legendFormat": "{{slice}}"
      }
     ]
    },
    {
     "title": "Rule Evaluator Iterations",
     "type": "graph",
     "description": "Rule-group evaluations \n - total\n - missed due to slow rule group evaluation\n - skipped due to throttled metric storage",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "short", "label": "iterations" }
     ],
     "targets": [
      {
       "expr": "sum(rate(prometheus_rule_group_iterations_total{job=~\"$job\", instance=~\"$instance\"}[$interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "sum(rate(prometheus_rule_group_iterations_missed_total{job=~\"$job\", instance=~\"$instance\"}[$interval]))",
       "legendFormat": "Missed"
      },
      {
       "expr": "sum(rate(prometheus_evaluator_iterations_skipped_total{job=~\"$job\", instance=~\"$instance\"}[5m]))",
       "legendFormat": "Skipped"
      }
     ]
    }
   ]
  },
  {
   "title": "remote storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sample success rate",
     "type": "gauge",
     "description": "Rate of dropped samples divided by sum of rate of succeeded and rate of dropped samples.",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "1 - (rate(prometheus_remote_storage_dropped_samples_total{job=\"$job\", instance=\"$instance\"}[$interval]) / (rate(prometheus_remote_storage_dropped_samples_total{job=\"$job\", instance=\"$instance\"}[$interval]) + rate(prometheus_remote_storage_succeeded_samples_total{job=\"$job\", instance=\"$instance\"}[$interval])))",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Shard rate",
     "type": "gauge",
     "description": "Actual divided by desired shards.",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
     "targets": [
      {
       "expr": "prometheus_remote_storage_shards{job=\"$job\", instance=\"$instance\"} / prometheus_remote_storage_shards_desired{job=\"$job\", instance=\"$instance\"}"
      }
     ]
    },
    {
     "title": "Actual shards",
     "type": "stat",
     "description": "The number of shards used for parallel sending to the remote storage.\n",
     "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_remote_storage_shards{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Actual"
      }
     ]
    },
    {
     "title": "Desired shards",
     "type": "stat",
     "description": "The number of shards that the queues shard calculation wants to run based on the rate of samples in vs. samples out.",
     "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_remote_storage_shards_desired{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Desired"
      }
     ]
    },
    {
     "title": "Max shards",
     "type": "stat",
     "description": "The maximum number of shards that the queue is allowed to run.",
     "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "prometheus_remote_storage_shards_max{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Actual"
      }
     ]
    },
    {
     "title": "Shard capacity",
     "type": "stat",
     "description": "The capacity of each shard of the queue used for parallel sending to the remote storage.",
     "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "prometheus_remote_storage_shard_capacity{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Samples sent succssfully",
     "type": "graph",
     "description": "Total number of samples successfully sent to remote storage.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "samples/s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_succeeded_samples_total{job=\"$job\", instance=\"$instance\"}[$interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Samples In",
     "type": "graph",
     "description": "Samples in to remote storage, compare to samples out for queue managers",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "samples/s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_samples_in_total{job=\"$job\", instance=\"$instance\"}[$interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Pending samples",
     "type": "graph",
     "description": "The number of samples pending in the queues shards to be sent to the remote storage.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short", "label": "samples/s" }
     ],
     "targets": [
      {
       "expr": "prometheus_remote_storage_pending_samples{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Dropped samples",
     "type": "graph",
     "description": "Total number of samples which were dropped after being read from the WAL before being sent via remote write.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_dropped_samples_total{job=\"$job\", instance=\"$instance\"}[$interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Batch send duration",
     "type": "graph",
     "description": "Duration of sample batch send calls to the remote storage.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[5m])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.9, sum by (le) (rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[5m])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.99, sum by (le) (rate(prometheus_remote_storage_sent_batch_duration_seconds_bucket{job=\"$job\", instance=\"$instance\"}[5m])))",
       "legendFormat": "P99"
      }
     ]
    },
    {
     "title": "Failed samples",
     "type": "graph",
     "description": "Total number of samples which failed on send to remote storage, non-recoverable errors.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "samples/s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_failed_samples_total{job=\"$job\", instance=\"$instance\"}[$interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Shard capacity",
     "type": "graph",
     "description": "The capacity of each shard of the queue used for parallel sending to the remote storage.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_remote_storage_shard_capacity{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Bytes sent",
     "type": "graph",
     "description": "The total number of bytes sent by the queue.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
     "yaxes": [
      { "format": "Bps", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_remote_storage_sent_bytes_total{job=\"$job\", instance=\"$instance\"}[$interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Shards: actual vs. desired",
     "type": "graph",
     "description": "Actual: The number of shards used for parallel sending to the remote storage.\n\nDesired: The number of shards that the queues shard calculation wants to run based on the rate of samples in vs. samples out.",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_remote_storage_shards{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Actual"
      },
      {
       "expr": "prometheus_remote_storage_shards_desired{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Desired"
      }
     ]
    },
    {
     "title": "Shards: min vs. max",
     "type": "graph",
     "description": "Min: The minimum number of shards that the queue is allowed to run.\n\nMax: The maximum number of shards that the queue is allowed to run.",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_remote_storage_shards_min{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Min"
      },
      {
       "expr": "prometheus_remote_storage_shards_max{job=\"$job\", instance=\"$instance\"}",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Failures and Errors",
     "type": "graph",
     "description": "All non-zero failures and errors",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short", "label": "Errors" }
     ],
     "targets": [
      {
       "expr": "sum(increase(net_conntrack_dialer_conn_failed_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "Failed Connections"
      },
      {
       "expr": "sum(increase(prometheus_rule_group_iterations_missed_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "Missed Iterations"
      },
      {
       "expr": "sum(increase(prometheus_rule_evaluation_failures_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "Evaluation"
      },
      {
       "expr": "sum(increase(prometheus_sd_azure_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "Azure Refresh"
      },
      {
       "expr": "sum(increase(prometheus_sd_consul_rpc_failures_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "Consul RPC"
      },
      {
       "expr": "sum(increase(prometheus_sd_dns_lookup_failures_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "DNS Lookup"
      },
      {
       "expr": "sum(increase(prometheus_sd_ec2_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "EC2 Refresh"
      },
      {
       "expr": "sum(increase(prometheus_sd_gce_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "GCE Refresh"
      },
      {
       "expr": "sum(increase(prometheus_sd_marathon_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "Marathon Refresh"
      },
      {
       "expr": "sum(increase(prometheus_sd_openstack_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "Openstack Refresh"
      },
      {
       "expr": "sum(increase(prometheus_sd_triton_refresh_failures_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "Triton Refresh"
      },
      {
       "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "Sample Limit"
      },
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "Duplicate Timestamp"
      },
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_bounds_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "Timestamp Out of Bounds"
      },
      {
       "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "Sample Out of Order"
      },
      {
       "expr": "sum(increase(prometheus_treecache_zookeeper_failures_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "Zookeeper"
      },
      {
       "expr": "sum(increase(prometheus_tsdb_compactions_failed_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "TSDB Compactions"
      },
      {
       "expr": "sum(increase(prometheus_tsdb_head_series_not_found{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "Series Not Found"
      },
      {
       "expr": "sum(increase(prometheus_tsdb_reloads_failures_total{instance=~\"$instance\"}[5m])) > 0",
       "legendFormat": "Reload"
      }
     ]
    }
   ]
  },
  {
   "title": "up",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Upness (stacked)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "none", "label": "Up" }
     ],
     "targets": [
      {
       "expr": "up{instance=~\"$instance\",job=~\"$job\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Storage Memory Chunks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "Chunks" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_head_chunks{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "series",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Series Count",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "Series" }
     ],
     "targets": [
      {
       "expr": "prometheus_tsdb_head_series{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Series Created / Removed",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "Series Count" }
     ],
     "targets": [
      {
       "expr": "sum( increase(prometheus_tsdb_head_series_created_total{instance=~\"$instance\"}[5m]) )",
       "legendFormat": "created"
      },
      {
       "expr": "sum( increase(prometheus_tsdb_head_series_removed_total{instance=~\"$instance\"}[5m]) )",
       "legendFormat": "removed"
      }
     ]
    }
   ]
  },
  {
   "title": "appended samples",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Appended Samples per Second",
     "type": "graph",
     "description": "Rate of total number of appended samples",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short", "label": "Samples / Second" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=~\"$job\",instance=~\"$instance\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scrape Sync Total",
     "type": "graph",
     "description": "Total number of syncs that were executed on a scrape pool.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "Syncs" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_target_scrape_pool_sync_total{job=~\"$job\",instance=~\"$instance\"}) by (scrape_job)",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    },
    {
     "title": "Target Sync",
     "type": "graph",
     "description": "Actual interval to sync the scrape pool.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short", "label": "Milliseconds" }
     ],
     "targets": [
      {
       "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{job=~\"$job\",instance=~\"$instance\"}[2m])) by (scrape_job) * 1000",
       "legendFormat": "{{scrape_job}}"
      }
     ]
    }
   ]
  },
  {
   "title": "scrapes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Scrape Duration",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short", "label": "Seconds" }
     ],
     "targets": [
      {
       "expr": "scrape_duration_seconds{instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scrape Duration by Job",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "scrape_duration_seconds", "legendFormat": "{{ job }}@{{ instance }}" }
     ]
    },
    {
     "title": "Rejected Scrapes",
     "type": "graph",
     "description": "Total number of rejected scrapes",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short", "label": "Scrapes" }
     ],
     "targets": [
      {
       "expr": "sum(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "exceeded sample limit"
      },
      {
       "expr": "sum(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "duplicate timestamp"
      },
      {
       "expr": "sum(prometheus_target_scrapes_sample_out_of_bounds_total{job=~\"$job\",instance=~\"$instance\"})",
       "legendFormat": "out of bounds"
      },
      {
       "expr": "sum(prometheus_target_scrapes_sample_out_of_order_total{job=~\"$job\",instance=~\"$instance\"}) ",
       "legendFormat": "out of order"
      }
     ]
    },
    {
     "title": "Samples Scraped by Job",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "scrape_samples_scraped", "legendFormat": "{{ job }}@{{ instance }}" }
     ]
    }
   ]
  },
  {
   "title": "notifications",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Notifications Sent",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short", "label": "Notifications" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_notifications_sent_total[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "config",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Minutes Since Successful Config Reload",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Minutes" }
     ],
     "targets": [
      {
       "expr": "(time() - prometheus_config_last_reload_success_timestamp_seconds{job=~\"$job\",instance=~\"$instance\"}) / 60",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Successful Config Reload",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short", "label": "Success" }
     ],
     "targets": [
      {
       "expr": "prometheus_config_last_reload_successful{job=~\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "garbage collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Rate / 2m",
     "type": "graph",
     "description": "GC invocation durations",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(go_gc_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\"}[2m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}