{
 "title": "Disponibilidade - Site Cherokee",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Status Geral",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "SOC - Acesso" },
     "item": {
      "filter": "Failed step of scenario \"Cherokee - Site\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SLA",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Desktop Central" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "itServiceFilter": "Site",
     "item": {
      "filter": "Failed step of scenario \"Desktop Central\"."
     },
     "options": {
      "acknowledged": 2,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default"
     },
     "proxy": { "filter": "" },
     "showProblems": "recent",
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 2
     }
    }
   ]
  },
  {
   "title": "Variação do Tempo de Resposta",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:622",
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "min",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1y" ],
       "text": "min(1y)"
      },
      {
       "$$hashKey": "object:623",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Mínima" ],
       "text": "setAlias(Mínima)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "SOC - Acesso" },
     "item": {
      "filter": "Response time for step \"Home - Cherokee\" of scenario \"Cherokee - Site\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:645",
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "max",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1y" ],
       "text": "max(1y)"
      },
      {
       "$$hashKey": "object:646",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Máxima" ],
       "text": "setAlias(Máxima)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "SOC - Acesso" },
     "item": {
      "filter": "Response time for step \"Home - Cherokee\" of scenario \"Cherokee - Site\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:668",
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1y" ],
       "text": "average(1y)"
      },
      {
       "$$hashKey": "object:669",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Média" ],
       "text": "setAlias(Média)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "SOC - Acesso" },
     "item": {
      "filter": "Response time for step \"Home - Cherokee\" of scenario \"Cherokee - Site\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Sites Hospedados" },
     "functions": [
      {
       "$$hashKey": "object:691",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Atual" ],
       "text": "setAlias(Atual)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "SOC - Acesso" },
     "item": {
      "filter": "Response time for step \"Home - Cherokee\" of scenario \"Cherokee - Site\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Histórico de Transferência",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Sites Hospedados" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "SOC - Acesso" },
     "item": {
      "filter": "Download speed for scenario \"Cherokee - Site\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Histórico de Tempo de Resposta",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Sites Hospedados" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "SOC - Acesso" },
     "item": {
      "filter": "Response time for step \"Home - Cherokee\" of scenario \"Cherokee - Site\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}