{
 "title": "Disponibilidade - Desktop Central",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Status Geral",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Desktop Central" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Failed step of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "SLA",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Desktop Central" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "itServiceFilter": "Desktop Central",
     "item": {
      "filter": "Failed step of scenario \"Desktop Central\"."
     },
     "options": {
      "acknowledged": 2,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default"
     },
     "proxy": { "filter": "" },
     "showProblems": "recent",
     "slaInterval": "none",
     "slaProperty": { "name": "SLA", "property": "sla" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 2
     }
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 16, "x": 8, "y": 0 },
   "options": { "content": "   " },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Variação do Tempo de Resposta - Passo 1",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:49",
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "min",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1y" ],
       "text": "min(1y)"
      },
      {
       "$$hashKey": "object:50",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Mínima" ],
       "text": "setAlias(Mínima)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Desktop Central - Home\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:72",
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "max",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1y" ],
       "text": "max(1y)"
      },
      {
       "$$hashKey": "object:73",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Máxima" ],
       "text": "setAlias(Máxima)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Desktop Central - Home\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:105",
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1y" ],
       "text": "average(1y)"
      },
      {
       "$$hashKey": "object:106",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Média" ],
       "text": "setAlias(Média)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Desktop Central - Home\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:128",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Atual" ],
       "text": "setAlias(Atual)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Desktop Central - Home\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Variação do Tempo de Resposta - Passo 2",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:173",
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "min",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1y" ],
       "text": "min(1y)"
      },
      {
       "$$hashKey": "object:174",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Mínima" ],
       "text": "setAlias(Mínima)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Desktop Central - SAML Redirect\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:196",
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "max",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1y" ],
       "text": "max(1y)"
      },
      {
       "$$hashKey": "object:197",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Máxima" ],
       "text": "setAlias(Máxima)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Desktop Central - SAML Redirect\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:219",
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1y" ],
       "text": "average(1y)"
      },
      {
       "$$hashKey": "object:220",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Média" ],
       "text": "setAlias(Média)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Desktop Central - SAML Redirect\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:242",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Atual" ],
       "text": "setAlias(Atual)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Desktop Central - SAML Redirect\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Variação do Tempo de Resposta - Passo 3",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:287",
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "min",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1y" ],
       "text": "min(1y)"
      },
      {
       "$$hashKey": "object:288",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Mínima" ],
       "text": "setAlias(Mínima)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Post Login Form\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:310",
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "max",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1y" ],
       "text": "max(1y)"
      },
      {
       "$$hashKey": "object:311",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Máxima" ],
       "text": "setAlias(Máxima)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Post Login Form\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:333",
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1y" ],
       "text": "average(1y)"
      },
      {
       "$$hashKey": "object:334",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Média" ],
       "text": "setAlias(Média)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Post Login Form\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:356",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Atual" ],
       "text": "setAlias(Atual)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Post Login Form\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Variação do Tempo de Resposta - Passo 4",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "clocks" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:401",
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "min",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1y" ],
       "text": "min(1y)"
      },
      {
       "$$hashKey": "object:402",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Mínima" ],
       "text": "setAlias(Mínima)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Redirect to SAML Login\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:424",
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "max",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "4d" ],
       "text": "max(4d)"
      },
      {
       "$$hashKey": "object:425",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Máxima" ],
       "text": "setAlias(Máxima)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Redirect to SAML Login\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:447",
       "def": {
        "category": "Aggregate",
        "defaultParams": [ "1m" ],
        "name": "average",
        "params": [
         { "name": "interval", "type": "string" }
        ]
       },
       "params": [ "1y" ],
       "text": "average(1y)"
      },
      {
       "$$hashKey": "object:448",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Média" ],
       "text": "setAlias(Média)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Redirect to SAML Login\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "functions": [
      {
       "$$hashKey": "object:470",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Atual" ],
       "text": "setAlias(Atual)"
      }
     ],
     "group": { "filter": "Linux servers" },
     "host": { "filter": "APP Server" },
     "item": {
      "filter": "Response time for step \"Redirect to SAML Login\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Histórico de Transferência",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Desktop Central" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "Download speed for step \"Desktop Central - Home\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "Download speed for step \"Desktop Central - SAML Redirect\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "Download speed for step \"Post Login Form\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "Download speed for step \"Redirect to SAML Login\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Histórico do Tempo de Resposta ",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "application": { "filter": "Desktop Central" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "Response time for step \"Desktop Central - Home\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "Response time for step \"Desktop Central - SAML Redirect\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "Response time for step \"Post Login Form\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Desktop Central" },
     "group": { "filter": "Linux servers" },
     "host": { "filter": "/.*/" },
     "item": {
      "filter": "Response time for step \"Redirect to SAML Login\" of scenario \"Desktop Central\"."
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "proxy": { "filter": "" },
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}