# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
  - job_name: 'node-exporter' 
    static_configs: 
      - targets: ['node-exporter:9100']
  - job_name: 'cAdvisor' 
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'grafana'
    scrape_interval: 15s
    scrape_timeout: 5s
    static_configs:
      - targets: ['host.docker.internal:3000']
  - job_name: 'mysql-exporter'
    static_configs:
      - targets: ['10.101.0.21:9104']
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['10.101.0.21:9187']
  - job_name: blackbox_http
    metrics_path: /probe
    params:
      module:
      - http_2xx
    relabel_configs:
    - source_labels:
      - __address__
      target_label: __param_target
    - source_labels:
      - __param_target
      target_label: instance
    - replacement: 10.101.0.21:9115	
      target_label: __address__
    static_configs:
    - targets:
      - http://10.101.0.21:9090/
      - http://node-exporter:9100/metrics
      - http://10.101.0.21:9104/metrics
      - http://host.docker.internal:3000/metrics
      - http://cadvisor:8080/metrics
      - http://10.101.0.21:9000/
      - http://10.101.0.21:3012/
      - http://10.101.0.21:1808/
      - http://10.101.0.21:1809/
  - job_name: blackbox_https
    scrape_timeout: 15s
    scrape_interval: 15s
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
    - targets:
      - https://www.cherokee.com.br/
      - https://dash.cherokee.com.br/
      - https://suporte.cherokee.com.br/
      - https://mon.cherokeesolutions.com.br/
    relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: 10.101.0.21:9115