version: "3"

networks:
  test-network:
    internal: true
services:

 mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: dbmysqld_exporter
    environment:
      - DATA_SOURCE_NAME='grafana_exporter:2xD*avipY-_y8OOBRJlZpAZ@(10.101.0.10:3306)/'
      - collect.info_schema.tablestats=true
      - collect.info_schema.userstats=true
      - collect.info_schema.query_response_time=true
      - collect.auto_increment.columns=true
      - collect.binlog_size=true
      - collect.perf_schema.eventsstatements=true
      - collect.perf_schema.eventswaits=true
      - collect.perf_schema.file_events=true
      - collect.perf_schema.indexiowaits=true
      - collect.perf_schema.tableiowaits=true
      - collect.perf_schema.tablelocks=true
    ports:
      - "9104:9104"
    networks:
      - test-network
      - default