version: "3"

networks:
  test-network:
    internal: true
services:

 mysqld_exporter:
    image: prom/mysqld-exporter:latest
    container_name: dbmysqld_exporter
    environment:
      - DATA_SOURCE_NAME=grafana_exporter:2xD*avipY-_y8OOBRJlZpAZ@(10.101.0.10:3306)/
    ports:
      - "9104:9104"
    networks:
      - test-network
      - default
    command: ["-web.listen-address=:9104", "-collect.global_status=true", "-collect.global_variables=false", "-collect.slave_status=false", "-collect.info_schema.tables=false", "-collect.binlog_size=false", "-collect.info_schema.processlist=false", "-collect.info_schema.userstats=false", "-collect.info_schema.tables=false", "-collect.auto_increment.columns=false", "-collect.info_schema.tablestats=false", "-collect.perf_schema.file_events=false", "-collect.perf_schema.eventsstatements=false", "-collect.perf_schema.indexiowaits=false", "-collect.perf_schema.tableiowaits=false", "-collect.perf_schema.tablelocks=false", "-collect.perf_schema.eventswaits=false"]