{
 "title": "Antivirus",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "origem",
    "label": "Origem",
    "query": "select concat(id,',',name) from source"
   }
  ]
 },
 "panels": [
  {
   "title": "Licenças Utilizadas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  usedslots\nFROM\n  av_license\nwhere\n  idCorp=$origem\n  \n"
    }
   ]
  },
  {
   "title": "Utilização %",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  100*usedslots/totalslots\nFROM\n  av_license\nwhere\n  idCorp=$origem\n  \n"
    }
   ]
  },
  {
   "title": "Versões do Produto",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  concat(productVersion,'') as metric,\n  count(*) as value\nFROM\n  av_endpoint\nWHERE\n  idCorp=$origem\ngroup by\n  productVersion\n"
    }
   ]
  },
  {
   "title": "Versões do Motor",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  concat(engineVersion,'') as metric,\n  count(*) as value\nFROM\n  av_endpoint\nWHERE\n  idCorp=$origem\ngroup by\n  engineVersion\n"
    }
   ]
  },
  {
   "title": "Estado do Endpoint",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 6, "w": 5, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "rawSql": "SELECT\n  now() as time,\n  concat(state,' ') as metric,\n  count(*) as value\nFROM\n  av_endpoint\nWHERE\n  idCorp=$origem\ngroup by\n  state\n"
    }
   ]
  },
  {
   "title": "Licenças Adquiridas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  totalslots\nFROM\n  av_license\nwhere\n  idCorp=$origem\n  \n"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "rawSql": "SELECT\n  name,so,ip,policyStatus,lastContact,lastUpdate,productVersion,engineVersion\nFROM\n  av_endpoint\nWHERE\n  idCorp=$origem\n"
    }
   ]
  }
 ]
}