version: "3.4"

networks:
  test-network:
    internal: true
    
configs:

  postgres_exporter_config:
    file: ./queries.yaml
services:
  postgres-exporter:
    image: wrouesnel/postgres_exporter:latest
    ports:
      - 9187:9187
    configs:
      - source: postgres_exporter_config
        target: /etc/postgres_exporter/queries.yaml
    deploy:
      mode: replicated
      replicas: 1
    environment:
      - DATA_SOURCE_NAME=postgresql://zabbix:Password!@10.101.0.10:5432/postgres?sslmode=disable
      - PG_EXPORTER_EXTEND_QUERY_PATH=/etc/postgres_exporter/queries.yaml
    networks:
      - test-network
      - default